import Head from 'next/head'
import Image from 'next/image'
import HeroContainer from '../components/organisms/HeroContainer/HeroContainer'
import AboutSection from '../components/organisms/AboutSection/AboutSection'
import Projects from'../components/organisms/ProjectsSection/Projects'
import Contact from '../components/organisms/ContactSection/Contact'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<HeroContainer/>
<AboutSection/>
<Projects/>
<Contact/>
</>
  )
}
